version: "3.9"

services:
  api:
    build: .
    container_name: markdown-blog-api

    ports:
      - "2000:2000"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: markdown-blog-db

    environment:
      POSTGRES_USER: khushi
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: markdown_blog_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: